--- 
- name: Copy artifact.tar.gz to EC2
  copy:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: Extract tar file
  unarchive: 
    src: "artifact.tar.gz"
    dest: "home/ubuntu/"

- name: start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start