- name : copy zip file 
  copy:
    src: project/artifact.tar.gz
    dest: home/ubuntu/artifact.tar.gz
    
- name: Extract tar
  unarchive:
    src: home/ubuntu/artifact.tar.gz
    dst:  home/ubuntu/
    remote_src: yes

- name: start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start