--- 
- name: Create directory
  file:
    path: ~/udapp
    state: directory

- name: Extract tar file into Ec2
  unarchive:
    src: "project/backend/artifact.tar.gz"
    dest:  "home/ubuntu/udapp"

- name: start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start