--- 
- name: copy file into EC2
  copy:
    src: "artifact.tar.gz"
    dst: "home/ubuntu/artifact.tar.gz"
     
- name: Extract tar file into Ec2
  unarchive:
    src: "home/ubuntu/artifact.tar.gz"
    dst:  "home/ubuntu/"
    remote_src: yes

- name: start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start